# Generated by Django 5.2.4 on 2025-07-19 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='number_of_occupants',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de personas que ocupan la unidad.', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
