# Generated by Django 5.2.4 on 2025-07-20 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_expense'),
        ('tenants', '0002_tenant_number_of_occupants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_occupants', models.PositiveSmallIntegerField(help_text='Número de personas que ocupan la unidad durante este arrendamiento.', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(help_text='Fecha de inicio del arrendamiento.')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de fin del arrendamiento. Si es null, el arrendamiento está activo.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='El inquilino que arrienda la unidad.', on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='tenants.tenant')),
                ('unit', models.ForeignKey(help_text='La unidad que está siendo arrendada.', on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Tenancy',
                'verbose_name_plural': 'Tenancies',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['unit', 'start_date'], name='tenants_ten_unit_id_9180a1_idx'), models.Index(fields=['unit', 'end_date'], name='tenants_ten_unit_id_8a01c7_idx')],
            },
        ),
    ]
