# Generated by Django 5.2.4 on 2025-07-20 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='El mes del ciclo de facturación (1-12).')),
                ('year', models.PositiveIntegerField(help_text='El año del ciclo de facturación.')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_review', 'En Revisión'), ('closed', 'Cerrado')], default='open', help_text='El estado actual del ciclo de facturación.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='La propiedad a la que pertenece este ciclo de facturación.', on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='properties.property')),
            ],
            options={
                'verbose_name': 'Billing Cycle',
                'verbose_name_plural': 'Billing Cycles',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('property', 'month', 'year'), name='unique_property_month_year_billing_cycle')],
            },
        ),
    ]
