# Generated by Django 5.2.4 on 2025-07-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('equal_division', 'División Equitativa')], help_text='El tipo de regla de asignación de gastos.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'type')},
            },
        ),
    ]
