# Generated by Django 5.2.4 on 2025-07-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('equal_division', 'División Equitativa'), ('occupant_proration', 'Prorrateo por Ocupante')], help_text='El tipo de regla de asignación de gastos.', max_length=50),
        ),
    ]
