# Generated by Django 5.2.4 on 2025-07-20 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_unit'),
        ('rules', '0002_alter_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('equal_division', 'División Equitativa'), ('occupant_proration', 'Prorrateo por Ocupante'), ('proportional_area', 'Ajuste Proporcional por Área'), ('consumption_adjustment', 'Ajuste por Consumo (Medidores)'), ('fixed_fee', 'Cuota Fija')], help_text='El tipo de regla de asignación de gastos.', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('electricity', 'Luz'), ('water', 'Agua'), ('arbitrios', 'Arbitrios'), ('motor', 'Motor'), ('maintenance', 'Mantenimiento'), ('gas', 'Gas')], help_text='El tipo de servicio al que se aplica la regla.', max_length=50)),
                ('rule_type', models.CharField(choices=[('equal_division', 'División Equitativa'), ('occupant_proration', 'Prorrateo por Ocupante'), ('proportional_area', 'Ajuste Proporcional por Área'), ('consumption_adjustment', 'Ajuste por Consumo (Medidores)'), ('fixed_fee', 'Cuota Fija')], help_text='El tipo de regla de asignación de gastos para este servicio.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='La propiedad a la que pertenece esta configuración de servicio.', on_delete=django.db.models.deletion.CASCADE, related_name='service_rules', to='properties.property')),
            ],
            options={
                'verbose_name': 'Service Rule Configuration',
                'verbose_name_plural': 'Service Rule Configurations',
                'constraints': [models.UniqueConstraint(fields=('property', 'service_type'), name='unique_property_service_rule')],
            },
        ),
    ]
